<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>61c169a9-e405-4563-80a4-6e283d8fe713</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="EFCore" Version="1.1.2" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.29" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.31" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.12">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational.Design" Version="2.0.0-preview1-final" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Design" Version="2.0.0-preview1-final" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BusinessLayer\BusinessLayer.csproj" />
    </ItemGroup>

</Project>
